kea_bank/employee_app/urls.py
from django.urls import path
from . import views

app_name = 'employee_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('customer/<int:pk>/', views.customer_detail, name="customer_detail"),
    path('update-customer/<int:pk>/',
         views.update_customer,
         name="update_customer"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('create-customer/', views.create_customer, name="create_customer"),
    path('account-detail/<int:account_number>/',
         views.account_detail,
         name="account_detail"),
    path('create-account/<int:pk>',
         views.create_account,
         name="create_account"),
    path('delete-account/<int:account_number>/<int:pk>',
         views.delete_account,
         name="delete_account")
]

kea_bank/kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('account/', include('login_app.urls')),
    path('', include('account_management_app.urls')),
    path('bank/', include('employee_app.urls')),
]

kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('', include('account_management_app.urls')),

]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
]

kea_bank/employee_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

kea_bank/employee_app/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse

from account_management_app.models import Customer, Account


@login_required(login_url='login_app:login')
def index(request):
    customers = Customer.objects.all()
    context = {
        'customers': customers,
    }

    return render(request, 'employee_app/index.html', context)


@login_required(login_url='login_app:login')
def my_profile(request):
    user = request.user
    return render(request, 'employee_app/my_profile.html', {'user': user})


@login_required(login_url='login_app:login')
def account_detail(request, account_number):
    account = Account.objects.get(account_number=account_number)
    transactions = account.get_transactions

    context = {'account': account, 'transactions': transactions}
    return render(request, 'employee_app/account_detail.html', context)


@login_required(login_url='login_app:login')
def create_customer(request):
    if (request.method == 'POST'):
        try:
            user = User.objects.create_user(
                request.POST['username'],
                email=request.POST['email'],
                password=request.POST['password'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'])
            customer = Customer(
                user=user,
                phone_number=request.POST['phone_number'],
                rank=request.POST['rank'],
            )
            customer.save()
            context = {
                'customer':
                customer,
                'success':
                'Customer ' + customer.user.username + ' created successfully'
            }
        except Exception:
            context = {'error': 'Error creating customer'}
            return render(request, 'employee_app/create_customer.html',
                          context)
    return render(request, 'employee_app/create_customer.html', {})


@login_required(login_url='login_app:login')
def customer_detail(request, pk):
    customer = Customer.objects.get(pk=pk)
    accounts = Account.objects.filter(user=customer.user)

    context = {
        'customer': customer,
        'accounts': accounts,
    }
    return render(request, 'employee_app/customer_detail.html', context)


@login_required(login_url='login_app:login')
def update_customer(request, pk):
    customer = Customer.objects.get(pk=pk)
    customer.rank = request.POST['rank']
    customer.save()
    accounts = Account.objects.filter(user=customer.user)

    context = {
        'customer': customer,
        'accounts': accounts,
    }
    return render(request, 'employee_app/customer_detail.html', context)


@login_required(login_url='login_app:login')
def create_account(request, pk):
    if request.method == "POST":
        customer = Customer.objects.get(pk=pk)
        Account.create(user=customer.user)
        context = {'customer': customer, 'success': 'Account created'}

    else:
        context = {'error': 'Something went wrong'}
    return HttpResponseRedirect(
        reverse('employee_app:customer_detail', kwargs={'pk': pk}), context)


@login_required(login_url='login_app:login')
def delete_account(request, account_number, pk):
    if request.method == "POST":
        account = Account.objects.get(account_number=account_number)
        account.delete()
        return HttpResponseRedirect(
            reverse('employee_app:customer_detail', kwargs={'pk': pk}))

kea_bank/employee_app/templates/employee_app/account_detail.html
{% extends "employee_app/base.html" %}
{% block content %}


<div clas="account-details">
    <h2>Account detail</h2>
    <p>Account number: {{account.account_number}}</p>
    <p>Balance: {{account.balance}} </p>
    <p>Is saving account: {{account.is_saving_account}}</p>
</div>

<div class="transaction">
    <h3>Transactions</h3>
    <table>
        <thead>
            <tr>

                <th>Date</th>
                <th>Amount</th>
                <th>Note</th>

            </tr>
        </thead>
        {% for transaction in transactions%}

        <tbody>
            <tr>
                <td>{{transaction.created_timestamp}}</td>
                <td>{{transaction.amount}}</td>
                <td>{{transaction.note}}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>





{% endblock %}

kea_bank/employee_app/templates/employee_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'style.css' %}" type="text/css" media="all">
    <script src="https://unpkg.com/htmx.org@1.8.0" defer></script>

    <title>Employee</title>
</head>
<body>

    <main >
        <div class="navigation">
            <a href="/">
                <img id="logo" src="{% static 'images/logo.png' %}" alt="Logo">
            </a>
            <nav>

                <a id="nav" href="{% url 'employee_app:index' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/user.png' %}" alt="profile">
                        <p>View all customers</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'employee_app:create_customer' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/plus.png' %}" alt="profile">
                        <p>Create customer </p>
                    </div>
                </a>
                <a id="nav" href="{% url 'employee_app:my_profile' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/profile.png' %}" alt="profile">
                        <p>My profile</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'login_app:logout' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/logout.png' %}" alt="profile">
                        <p>Sign out</p>
                    </div>
                </a>
            </nav>
        </div>
    
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    
</body>
</html>

kea_bank/employee_app/templates/employee_app/create_customer.html
{% extends "employee_app/base.html" %}
{% block content %}

<div>
    <h1>Create customer</h1>
<form action="/bank/create-customer/" method="post">
                      {% csrf_token %}


        <input id="username" name="username" type="text"
                placeholder="Username" value="username" required>

        <input id ="first_name" name="first_name" type="text"
                placeholder="First name" value="first_name" required>

        <input id="last_name" name="last_name" type="text"
                placeholder="Last name" value="last_name" required>

        <input id="email" name="email" type="text"
                placeholder="Email" value="email" required>

        <input id="password" name="password" type="text"
                placeholder="Password" value="password123" required>

        <input id="phone_number" name="phone_number" value="31360873" type="text"
                placeholder="Phone number" required>


        <p style="color:green">{{ success }}</p>
        <p> {{ error }} </p>



<label for="rank">Choose a rank:</label>

<select name="rank" id="rank">
  <option value="basic">Basic</option>
  <option value="silver">Silver</option>
  <option value="gold">Gold</option>
</select>

        <button type="submit">Submit</button>

</form>
</div>
{% endblock%}

kea_bank/employee_app/templates/employee_app/customer_detail.html
{% extends "employee_app/base.html" %}
{% block content %}

<h2>Customer detail</h2>

<div class="customer-info">
    <p>Username: {{customer.user.username}}</p>
    <p>First name: {{customer.user.first_name}}</p>
    <p>Last name: {{customer.user.last_name}}</p>
    <p>Email: {{customer.user.email}}</p>
    <p>Rank: {{customer.rank}}</p>

    <form action="{% url 'employee_app:update_customer' pk=customer.pk %}" method="POST">
        {% csrf_token %}
    <select name="rank">
        <option {%if customer.rank == "basic"%} selected="selected" {% endif %} value="basic">Basic</option>
        <option {%if customer.rank == "silver"%} selected="selected" {% endif %} value="silver">Silver</option>
        <option {%if customer.rank == "gold"%} selected="selected" {% endif %} value="gold">Gold</option>
    </select>
    <br><br>
    <input type="submit" value="Save changes">
    </form>

</div>

<div class="accounts">
    <h3>Accounts</h3>

    <form action="{% url 'employee_app:create_account' pk=customer.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Create account"></input>
    </form>

    <div class="account-wrapper">
        {% for account in accounts %}

        <div class="account-list-wrapper">
            <a id="account-number" href="{% url 'employee_app:account_detail' account_number=account.account_number  %}">
                {{account.account_number}}
            </a> 

            <form action="{% url 'employee_app:delete_account' account_number=account.account_number pk=customer.pk %}" method="POST">
                {% csrf_token %}
                <input id="delete-button" type="submit" value="Delete">
            </form>

        </div>


        

        {% endfor %}
    </div>


</div>
{% endblock %}

kea_bank/employee_app/templates/employee_app/index.html
{% extends "employee_app/base.html" %}
{% block content %}


<h2>All customers</h2>

{% for customer in customers %}

<div class="user-wrapper-link">
    <a href="{% url 'employee_app:customer_detail' pk=customer.pk %}">
        {{customer.user.username}}
    </a>
</div>



{% endfor %}



{% endblock %}

kea_bank/employee_app/templates/employee_app/my_profile.html
{% extends "employee_app/base.html" %}
{% block content %}

<div>
    <h1 class="heading">My profile</h1>
        <div>
            <p>First name: {{user.first_name}}</p>
            <p>Last name: {{user.last_name}}</p>
            <p>Email: {{user.email}}</p>
        </div>
    <div>       
    </div>
</div>


{% endblock %}