account_management_app/urls.py
from django.urls import path
from . import views

app_name = 'account_management_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('transfer/<int:account_number>/', views.transfer, name="transfer"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('account_details/<int:account_number>/', views.account_details, name="account_details"),
    path('loan/<int:account_number>/', views.loan, name="loan"),
    path('loan/<int:account_number>/pay/', views.pay_back_loan, name="pay_back_loan"),
]

kea_bank/account_management_app/urls.py
from django.urls import path
from . import views
from .api import Reserve, GetUpdateStatus

app_name = 'account_management_app'

urlpatterns = [
    path('', views.index, name="index"),
    path('login-success/', views.login_success, name="login_success"),
    path('transfer/<int:account_number>/', views.transfer, name="transfer"),
    path('transfer/external/<int:account_number>/',
         views.external_transfer,
         name="external_transfer"),
    path('my-profile/', views.my_profile, name="my_profile"),
    path('chatbot/', views.chatbot_conv, name="chatbot_conv"),
    path('message/', views.chatbot_messages, name="chatbot_messages"),
    path('account-details/<int:account_number>/',
         views.account_details,
         name="account_details"),
    path('loan/<int:account_number>/', views.loan, name="loan"),
    path('loan/<int:account_number>/pay/',
         views.pay_back_loan,
         name="pay_back_loan"),
    path('my-savings/', views.my_savings, name="my_savings"),
    path('create-saving-account/',
         views.create_saving_account,
         name="create_saving_account"),
    path('saving-account-detail/<int:account_number>/',
         views.saving_account_detail,
         name="saving_account_detail"),
    path('delete-account/<int:account_number>',
         views.delete_saving_account,
         name="delete_saving_account"),
    path('saving-account-transfer/<int:account_number>/',
         views.saving_account_transfer,
         name="saving_account_transfer"),
    path('api/v1/transaction', Reserve.as_view()),  # post
    path('api/v1/transaction/<uuid:token>/',
         GetUpdateStatus.as_view()),  # get, put
]

kea_bank/kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('account/', include('login_app.urls')),
    path('', include('account_management_app.urls')),
    path('bank/', include('employee_app.urls')),
]

kea_bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('', include('account_management_app.urls')),

]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('logout/', views.logout, name='logout'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
]

account_management_app/views.py
from decimal import Decimal
from django.shortcuts import render
from . models import Account
from django.contrib.auth.decorators import login_required


@login_required(login_url='login_app:login')
def index(request):
    user = request.user
    accounts = Account.objects.filter(user=user)
    total_balance = user.customer.total_balance

    return render(request, 'account_management_app/index.html', {
        'accounts': accounts,
        'customer': user,
        'total_balance': total_balance
    })

def make_loan(request, account_number, pay_back=False):
    customer = request.user.customer
    my_account = Account.objects.get(account_number=account_number)
    amount_owed = my_account.get_amount_owed()
    loan_transactions = my_account.get_loan_transactions()

    if request.method == 'POST':
        if customer.rank == "basic":
            print('Cant apply for loan. Please upgrade your user rank.')
        amount = Decimal(request.POST['amount'])
        # gets banks operational account
        our_account = Account.objects.filter(is_customer=False)[0]
        if pay_back:
            if amount_owed >= amount:
                my_account.make_payment(amount, our_account.account_number, is_loan=True)
            else:
                # TODO: display error message
                print('Cant return more than what you owe')
        else:
            our_account.make_payment(amount, account_number, is_loan=True)
        transactions = my_account.get_transactions
        return render(request, 'account_management_app/account_details.html', {
            'account': my_account,
            'transactions': transactions,
            'amount_owed': amount_owed,
            'loan_transactions': loan_transactions
        })
    else:
        return render(request, 'account_management_app/loan.html', {
            'account_number': account_number,
            'customer': customer,
            'amount_owed': amount_owed,
            'loan_transactions': loan_transactions
        })

@login_required(login_url='login_app:login')
def loan(request, account_number):
    return make_loan(request, account_number=account_number)

@login_required(login_url='login_app:login')
def pay_back_loan(request, account_number):
    return make_loan(request, account_number=account_number, pay_back=True)

@login_required(login_url='login_app:login')
def transfer(request, account_number):
    customer = request.user.customer
    my_account = Account.objects.get(account_number=account_number)
    accounts = Account.objects.filter(user=request.user)
   
    try:
        my_account.make_payment(Decimal(request.POST['amount']), request.POST['account_number'])
    except Exception as e:
        context['error'] = f'there was an error: {e}'

    context = {
        'accounts': accounts,
        'total_balance': customer.total_balance
    }
    return render(request, 'account_management_app/index.html', context)

@login_required(login_url='login_app:login')
def account_details(request, account_number):
    account = Account.objects.get(account_number = account_number)
    transactions = account.get_transactions

    return render(request, 'account_management_app/account_details.html', {
        'account': account,
        'transactions': transactions
    })

@login_required(login_url='/accounts/login/')
def my_profile(request):
    user = request.user
    return render(request, 'account_management_app/my_profile.html', {
        'customer': user.customer,
        'user': user
    })

kea_bank/account_management_app/views.py
from decimal import Decimal
import uuid
from django.shortcuts import render, redirect
from .models import Account, ExternalLedgerMetadata
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import chatbot


def is_user_customer_check(user):
    return hasattr(user, "customer")


@login_required(login_url='login_app:login')
def login_success(request):
    """
    Redirects users based on whether they are a customer or employee
    """
    if request.user.is_superuser:
        return HttpResponseRedirect(reverse('admin:index'))
    elif is_user_customer_check(request.user):
        # user is a customer
        return redirect("account_management_app:index")
    else:
        return redirect("employee_app:index")


@login_required(login_url='login_app:login')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def index(request):
    user = request.user
    accounts = user.customer.get_ordinary_accounts()
    total_balance = user.customer.total_balance_bank_accounts

    return render(request, 'account_management_app/index.html', {
        'accounts': accounts,
        'customer': user,
        'total_balance': total_balance
    })


def make_loan(request, account_number, pay_back=False):
    customer = request.user.customer
    my_account = Account.objects.get(account_number=account_number)
    amount_owed = my_account.get_amount_owed()
    loan_transactions = my_account.get_loan_transactions()

    if request.method == 'POST':
        amount = Decimal(request.POST['amount'])
        external_banks = request.user.customer.get_external_banks()
        # gets banks operational account
        our_account = customer.get_bank_operational_account()
        if pay_back:
            my_account.pay_back_loan(amount, amount_owed)
        else:
            our_account.make_payment(amount, account_number, is_loan=True)
        # gets transactions after making payment
        transactions = my_account.get_transactions()
        return render(
            request, 'account_management_app/account_details.html', {
                'account': my_account,
                'transactions': transactions,
                'amount_owed': amount_owed,
                'loan_transactions': loan_transactions,
                'external_banks': external_banks
            })
    else:
        return render(
            request, 'account_management_app/loan.html', {
                'account_number': account_number,
                'customer': customer,
                'amount_owed': amount_owed,
                'loan_transactions': loan_transactions
            })


@login_required(login_url='login_app:login')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def loan(request, account_number):
    return make_loan(request, account_number=account_number)


@login_required(login_url='login_app:login')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def pay_back_loan(request, account_number):
    return make_loan(request, account_number=account_number, pay_back=True)


@login_required(login_url='login_app:login')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def transfer(request, account_number):
    customer = request.user.customer
    my_account = Account.objects.get(account_number=account_number)
    accounts = customer.get_ordinary_accounts()

    context = {
        'accounts': accounts,
        'total_balance': customer.total_balance_bank_accounts
    }
    try:
        my_account.make_payment(Decimal(request.POST['amount']),
                                request.POST['account_number'])
        context['total_balance'] = customer.total_balance_bank_accounts
    except Exception as e:
        context['error'] = f'There was an error: {e}'

    return render(request, 'account_management_app/index.html', context)


@login_required(login_url='login_app:login')
def account_details(request, account_number):
    account = Account.objects.get(account_number=account_number)
    transactions = account.get_transactions()
    external_banks = request.user.customer.get_external_banks()

    return render(
        request, 'account_management_app/account_details.html', {
            'account': account,
            'transactions': transactions,
            'external_banks': external_banks
        })


@login_required(login_url='/accounts/login/')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def my_profile(request):
    user = request.user
    return render(request, 'account_management_app/my_profile.html', {
        'customer': user.customer,
        'user': user
    })


@login_required(login_url='/accounts/login/')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def my_savings(request):
    user = request.user
    total_balance = user.customer.total_balance_saving_accounts
    accounts = Account.objects.filter(user=user, is_saving_account=True)

    return render(request, 'account_management_app/my_savings.html', {
        'accounts': accounts,
        'total_balance': total_balance
    })


@login_required(login_url='/accounts/login/')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def create_saving_account(request):
    Account.create(user=request.user, is_saving_account=True)
    return HttpResponseRedirect(reverse('account_management_app:my_savings'))


@login_required(login_url='/accounts/login/')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def saving_account_detail(request, account_number):
    account = Account.objects.get(account_number=account_number,
                                  is_saving_account=True)
    all_accounts = Account.objects.filter(user=request.user,
                                          is_saving_account=False)

    return render(request, 'account_management_app/saving_account_detail.html',
                  {
                      'account': account,
                      'all_accounts': all_accounts
                  })


@login_required(login_url='/accounts/login/')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def delete_saving_account(request, account_number):
    if request.method == "POST":
        account = Account.objects.get(account_number=account_number)
        if account.balance == 0:
            account.delete()
            return HttpResponseRedirect(
                reverse('account_management_app:my_savings'))
        else:
            user = request.user
            total_balance = user.customer.total_balance_saving_accounts
            accounts = Account.objects.filter(user=user, is_saving_account=True)

            return render(request, 'account_management_app/my_savings.html',
                          { 'user': user,
                            'total_balance': total_balance,
                            'accounts': accounts,
                            'error': 'You cannot delete an account with a balance'
                            })


@login_required(login_url='/accounts/login/')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def saving_account_transfer(request, account_number):
    customer = request.user.customer
    saving_account = Account.objects.get(account_number=account_number,
                                         is_saving_account=True)
    context = {}
    if request.method == 'POST':
        transfer_account_number = request.POST.get('accounts')
        if transfer_account_number:
            amount = Decimal(request.POST['amount'])
        else:
            return render(
                request, 'account_management_app/saving_account_detail.html', {
                    'account': saving_account,
                    'message':
                    'Please select an amount and account to transfer to'
                })
        transfer_account = Account.objects.get(
            account_number=transfer_account_number)
        all_accounts = Account.objects.filter(user=request.user,
                                              is_saving_account=False)

        try:
            transfer_account.make_payment(amount,
                                          saving_account.account_number,
                                          is_loan=False,
                                          is_saving_account=True)
            message = 'Amount was successfully transferred to saving account'
        except Exception:
            message = 'Error occurred, balance is too low'

        transactions = saving_account.get_transactions()
        context = {
            'account': saving_account,
            'transactions': transactions,
            'customer': customer,
            'message': message,
            'all_accounts': all_accounts
        }
    return render(request, 'account_management_app/saving_account_detail.html',
                  context)


@login_required(login_url='login_app:login')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def chatbot_conv(request):
    user = request.user

    conversation = chatbot.get_all_conv(user)
    context = {'conversation': conversation}
    return render(request, 'account_management_app/chatbot.html', context)


@login_required(login_url='login_app:login')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def chatbot_messages(request):
    user = request.user

    if (request.method == 'POST'):
        message = request.POST['message']
        chatbot.save_conversation(user, message)
        return HttpResponseRedirect(
            reverse('account_management_app:chatbot_conv'))
    else:
        return HttpResponseRedirect(
            reverse('account_management_app:chatbot_conv'))


@login_required(login_url='login_app:login')
@user_passes_test(is_user_customer_check, login_url='login_app:login')
def external_transfer(request, account_number):

kea_bank/account_management_app/templates/account_management_app/account_details.html
<div id="modal" _="on closeModal">
	<div class="modal-content">
        <div id="account_{{account.account_number}}">
            <section class="col-element">
                <div class="top-details">
                    <h2>{{account.account_number}}</h2>    
                    <a id="close-popup" href="/">Close</a>
                </div>
                <div class="balance">
                    <p>Balance: {{account.balance}} </p>
                </div>
            </section>
        
            <section class="popup-wrapper">
                <div class="transfering-wrapper">
                    <h3>Transfer within our bank</h3>
                    <div class="sending-money">
                        <form action="{% url 'account_management_app:transfer' account.account_number %}" method="POST">
                            {% csrf_token %}
                            <input name="amount" type="number" placeholder="Amount">
                            <input name="account_number" type="text" placeholder="Account number">
                            <input name="note" type="text" placeholder="Note">
                            <button>
                                Send
                            </button>
                        </form>
                    </div>
                    <hr>
                    <h3>Transfer to other banks</h3>
                    <div class="sending-money">
                        <form action="{% url 'account_management_app:external_transfer' account.account_number %}" method="POST">
                            {% csrf_token %}
                            <select name="bank_id">
                                {% for bank in external_banks %}
                                  <option value="{{ bank.bank_id }}">{{ bank.name }}</option>
                                {% endfor %}
                            </select>
                            <input name="amount" type="number" placeholder="Amount">
                            <input name="account_number" type="text" placeholder="Account number">
                            <button>
                                Send
                            </button>
                        </form>
                    </div>
                    <hr>
    
                    <h3>All transactions</h3>
                    <table>
                        <thead>
                            <tr>
    
                                <th>Date</th>
                                <th>Amount</th>
                                <th>Note</th>
                            </tr>
                        </thead>
                        {% for transaction in transactions%}
    
                        <tbody>
                            <tr>
                                <td>{{transaction.created_timestamp}}</td>
                                <td>{{transaction.amount}}</td>
                                <td>{{transaction.note}}</td>
                            </tr>
                        </tbody>
                        {% endfor %}
                    </table>
                </div>

                <section class="col-element">
                    <h3>Loan</h3>
                    <div 
                        id="loan_container"
                        hx-swap="outerHTML"
                        hx-get="{% url 'account_management_app:loan' account_number=account.account_number %}"
                        hx-trigger="load">
                    </div>
                </section>
            </section>

                </section>
    
                    




            

	</div>
</div>

kea_bank/account_management_app/templates/account_management_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{% static 'style.css' %}" type="text/css" media="all">
    <script src="https://unpkg.com/htmx.org@1.8.0" defer></script>

    <title>Bank</title>
</head>
<body>

    <main >
        <div class="navigation">
            <a href="/">
                <img id="logo" src="{% static 'images/logo.png' %}" alt="Logo">
            </a>
            <nav>

                <a id="nav" href="/">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/dashboard.png' %}" alt="dashboard">
                        <p>Dashboard</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'account_management_app:my_profile' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/user.png' %}" alt="profile">
                        <p>My profile</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'account_management_app:my_savings' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/savings.png' %}" alt="profile">
                        <p>My savings</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'account_management_app:chatbot_conv' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/chat.png' %}" alt="profile">
                        <p>Chatbot</p>
                    </div>
                </a>
                <a id="nav" href="{% url 'login_app:logout' %}">
                    <div class="link-wrapper">
                        <img id="icon" src="{% static 'images/logout.png' %}" alt="profile">
                        <p>Sign out</p>
                    </div>
                </a>
            </nav>
        </div>
    
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    
</body>
</html>

kea_bank/account_management_app/templates/account_management_app/chatbot.html
{% extends "account_management_app/base.html" %}
{% block content %}
{% load static %}

<h3>Welcome to Chatbot</h3>

<div class="chat-wrapper">
    <div class="chat-header">
        <img id="icon-chatbot" src="{% static 'images/chatbot.png' %}" alt="profile">
        <p>Chatbot</p>
        <img id="icon" src="{% static 'images/dot.png' %}" alt="profile">
    </div>

    <div class="conversation-wrapper">
    {% for conv in conversation %}
        {% for value in conv %}

        <div class="question">
            {{value.question}}
        </div>
        <div class="response">
            {{value.response}}
        </div>
        {% endfor %}
    {% endfor %}



    </div>

    <form id="chatbot_form" action="/message/" method="post">
        {% csrf_token %}
        
        <div class="input-wrapper">
            <input type="text" name="message" required>
            <button type="submit">Send</button>
        </div>
    </form>
</div>

<div class="question-example">
    <h3>Chatbot can answer to this questions:</h3>
    <p>How do I transfer money?</p>
    <p>How do I make a loan?</p>
    <p>How do I return money?</p>
    <p>How do I add money to my transfer account?</p>
</div>



{% endblock %}

kea_bank/account_management_app/templates/account_management_app/index.html
{% extends "account_management_app/base.html" %}
{% block content %}

<div class="account-wrapper">
    <h1>Dashboard</h1>
    <p> Welcome {{customer}} !</p>

    <div class="total-balance">
        <p>YOUR TOTAL BALANCE</p>
        <p id="amount_balance">{{total_balance}}</p>
    </div>

    <div class="payment-list">
        <div class="accounts">
            <h2>Your bank accounts</h2>
            {% for account in accounts %}
        
            <div class="account_number" id="{{account.account_number }}"
                 class="clickable"
                 hx-get="{% url 'account_management_app:account_details' account.account_number %}"
                 hx-trigger="click"
                 hx-target="this"
                 hx-swap="outerHTML">
                <div>Account number: {{account.account_number}}</div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if error %}
        {{ error }}
    {% endif %}

</div>


{% endblock %}

kea_bank/account_management_app/templates/account_management_app/loan.html
<div id="loan">
    {% if customer.rank == "basic" %}
        <p>You can't make a loan</p>
    {% else %}

    <p>Take loan money</p>
    <form>
        {% csrf_token %}
            <input type="number" name="amount" placeholder="Amount" />
            <button
            hx-post="{% url 'account_management_app:loan' account_number=account_number %}"
            hx-trigger="click"
            hx-target="#account_{{account_number}}"
            hx-swap="outerHTML">
                Take loan
            </button>
    </form>
    <hr>

    <p>Amount you have to return: {{amount_owed}}</p>
    <form>
        {% csrf_token %}
            <input type="number" name="amount" placeholder="Amount" />
            <button
            hx-post="{% url 'account_management_app:pay_back_loan' account_number=account_number %}"
            hx-trigger="click"
            hx-target="#account_{{account_number}}"
            hx-swap="outerHTML">
                Pay back
            </button>
    </form>
    <hr>

    {% endif %}

    <h3>Your loan history </h3>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Amount</th>
            </tr>
        </thead>
        {% for transaction in loan_transactions %}
        <tbody>
            <tr>
                <td>{{transaction.created_timestamp}}</td>
                <td>{{transaction.amount}}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>


</div>

kea_bank/account_management_app/templates/account_management_app/my_profile.html
{% extends "account_management_app/base.html" %}
{% block content %}

<div>
    <h1 class="heading">My profile</h1>
    <div>
        <p>First name: {{user.first_name}}</p>

        <p>Last name: {{user.last_name}}</p>
    
        <p>Phone number: {{customer.phone_number}}</p>
        <p>Rank: {{customer.rank}}</p>

    </div>
    <div>
        <a id="nav" href="{% url 'two_factor:setup' %}">
            <strong>Multifactor authentication</strong>
        </a>
    </div>


    <div>
        
    </div>


</div>


{% endblock %}

kea_bank/account_management_app/templates/account_management_app/my_savings.html
{% extends "account_management_app/base.html" %}
{% block content %}

<h2>My savings</h2>

<div class="total-balance">
    <p>YOUR TOTAL AMOUNT IN SAVINGS</p>
    <p id="amount_balance">{{total_balance}}</p>
</div>

<form action="{% url 'account_management_app:create_saving_account' %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Create saving account"></input>
</form>

<div class="account-wrapper">
    {% for account in accounts %}
    <div class="account-list-wrapper">
        <a id="account-number" href="{% url 'account_management_app:saving_account_detail' account_number=account.account_number  %}">
            Account number: {{account.account_number}}
        </a> 
        <form action="{% url 'account_management_app:delete_saving_account' account_number=account.account_number  %}" method="POST">
            {% csrf_token %}
            <input id="delete-button" type="submit" value="Delete">
        </form>
    </div>
    {% endfor %}
</div>
<div class="error" style="color:red">
    {{ error }}
</div>

{% endblock %}

kea_bank/account_management_app/templates/account_management_app/saving_account_detail.html
{% extends "account_management_app/base.html" %}
{% block content %}

<h3>Saving account detail</h3>
<div clas="account-details">
    <h2>Account detail</h2>
    <p>Account number: {{account.account_number}}</p>
    <p>Balance: {{account.balance}} </p>
    <p>Is saving account: {{account.is_saving_account}}</p>
</div>

<h3>Transfering money to saving account</h3>
<form id="saving-transfer" action="{% url 'account_management_app:saving_account_transfer' account.account_number  %}" method="POST">
    {% csrf_token %}
    <label for="amount">Type the amount you want to transfer</label>
    <input type="number" name="amount" placeholder="Amount">
    <label for="accounts"> Choose the account you want to transfter from</label>
    <select name="accounts">
        {% for account_to_transfer in all_accounts %}

        <option  value="{{account_to_transfer.account_number }}">{{account_to_transfer.account_number}}</option>
        {% endfor %}

    </select>

    <input type="submit" value="Add">
</form>

<div class="error" style="color:red">
    {{message}}
    {{ error }}
</div>


{% endblock %}